"""Add MediaAsset table

Revision ID: 2013b0dbd1a4
Revises: 20562da50bdd
Create Date: 2026-04-11 10:55:01.537977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2013b0dbd1a4'
down_revision: Union[str, None] = '20562da50bdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_level', sa.String(length=20), nullable=True),
    sa.Column('app_id', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('meta_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_app_id'), 'media_assets', ['app_id'], unique=False)
    op.create_index(op.f('ix_media_assets_is_deleted'), 'media_assets', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_media_assets_target_id'), 'media_assets', ['target_id'], unique=False)
    op.create_index(op.f('ix_media_assets_user_id'), 'media_assets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_assets_user_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_target_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_is_deleted'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_app_id'), table_name='media_assets')
    op.drop_table('media_assets')
    # ### end Alembic commands ###
