"""Refactor service architecture to bundle-driven arrays

Revision ID: 20562da50bdd
Revises: 86385fe70915
Create Date: 2026-04-10 19:57:27.914380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20562da50bdd'
down_revision: Union[str, None] = '86385fe70915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('service_app_child_app_id_fkey'), 'service_app', type_='foreignkey')
    op.drop_column('service_app', 'child_app_id')
    op.add_column('service_instance', sa.Column('service_app_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint(op.f('service_instance_root_app_id_fkey'), 'service_instance', type_='foreignkey')
    op.drop_column('service_instance', 'root_app_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_instance', sa.Column('root_app_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('service_instance_root_app_id_fkey'), 'service_instance', 'service_app', ['root_app_id'], ['id'])
    op.drop_column('service_instance', 'service_app_ids')
    op.add_column('service_app', sa.Column('child_app_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('service_app_child_app_id_fkey'), 'service_app', 'service_app', ['child_app_id'], ['id'])
    # ### end Alembic commands ###
