"""Add redirect_url to Page

Revision ID: 28c668d50cbb
Revises: 965e6fb71222
Create Date: 2026-03-12 16:31:16.352368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28c668d50cbb'
down_revision: Union[str, None] = '965e6fb71222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('redirect_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'redirect_url')
    # ### end Alembic commands ###
