"""restore strict not null constraints

Revision ID: 389f476f6040
Revises: 92434c71bf3a
Create Date: 2026-03-02 20:27:56.932923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '389f476f6040'
down_revision: Union[str, None] = '92434c71bf3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('answer', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('board_config', 'create_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('comment', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dayoff', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('dayoff', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('post', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('post', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('push_subscription', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('question', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('push_subscription', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('post', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('post', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dayoff', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('dayoff', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('comment', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('board_config', 'create_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('answer', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('alert', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
