"""Add position to alert

Revision ID: 5f66f11ed7a4
Revises: 3f166e79feb7
Create Date: 2026-02-26 17:00:14.566289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f66f11ed7a4'
down_revision: Union[str, None] = '3f166e79feb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert', sa.Column('position', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert', 'position')
    # ### end Alembic commands ###
