"""Add thumbnail_filename to QuestionImage

Revision ID: 618caad9acec
Revises: 68f97d38acc3
Create Date: 2026-02-18 12:48:22.817297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '618caad9acec'
down_revision: Union[str, None] = '68f97d38acc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_image', sa.Column('thumbnail_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_image', 'thumbnail_filename')
    # ### end Alembic commands ###
