"""Add missing fields to Alert model

Revision ID: 6bc38bc7518f
Revises: 7fecfa73dc94
Create Date: 2026-03-03 17:08:01.585102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bc38bc7518f'
down_revision: Union[str, None] = '7fecfa73dc94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert', sa.Column('target_users', sa.String(), nullable=True))
    op.add_column('alert', sa.Column('confirm_text', sa.String(), nullable=True))
    op.add_column('alert', sa.Column('reset_sec', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert', 'reset_sec')
    op.drop_column('alert', 'confirm_text')
    op.drop_column('alert', 'target_users')
    # ### end Alembic commands ###
