"""refactor_service_architecture

Revision ID: 86385fe70915
Revises: 124736f8747b
Create Date: 2026-04-09 12:12:05.632814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86385fe70915'
down_revision: Union[str, None] = '124736f8747b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('engine_id', sa.String(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('child_app_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_app_id'], ['service_app.id'], ),
    sa.ForeignKeyConstraint(['engine_id'], ['service_engine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('root_app_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['root_app_id'], ['service_app.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_service_binding_target_app'), table_name='service_binding')
    op.drop_index(op.f('ix_service_binding_target_id'), table_name='service_binding')
    op.drop_table('service_binding')
    op.add_column('board_config', sa.Column('service_instance_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'board_config', 'service_instance', ['service_instance_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'board_config', type_='foreignkey')
    op.drop_column('board_config', 'service_instance_id')
    op.create_table('service_binding',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('target_app', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('engine_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('custom_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('min_write_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['engine_id'], ['service_engine.id'], name=op.f('service_binding_engine_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('service_binding_pkey'))
    )
    op.create_index(op.f('ix_service_binding_target_id'), 'service_binding', ['target_id'], unique=False)
    op.create_index(op.f('ix_service_binding_target_app'), 'service_binding', ['target_app'], unique=False)
    op.drop_table('service_instance')
    op.drop_table('service_app')
    # ### end Alembic commands ###
