"""Add is_active to Page

Revision ID: 965e6fb71222
Revises: 97d0c1882d2a
Create Date: 2026-03-12 15:33:39.782823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '965e6fb71222'
down_revision: Union[str, None] = '97d0c1882d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'is_active')
    # ### end Alembic commands ###
