"""Add soft delete to Page

Revision ID: 97d0c1882d2a
Revises: f5b490ab5c55
Create Date: 2026-03-12 14:41:32.905835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97d0c1882d2a'
down_revision: Union[str, None] = 'f5b490ab5c55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('page', sa.Column('delete_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'delete_date')
    op.drop_column('page', 'is_deleted')
    # ### end Alembic commands ###
