"""add user profile and authority fields

Revision ID: 9cf6720485d0
Revises: 07fe7114b819
Create Date: 2026-03-02 11:24:26.671807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cf6720485d0'
down_revision: Union[str, None] = '07fe7114b819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rank_level', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('employee_no', sa.String(), nullable=True),
    sa.Column('resident_no', sa.String(), nullable=True),
    sa.Column('joined_date', sa.Date(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('account_no', sa.String(), nullable=True),
    sa.Column('admin_memo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('users', sa.Column('real_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('users', 'real_name')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
