"""update menu table with min_rank

Revision ID: 9e18ac9c3788
Revises: 9cf6720485d0
Create Date: 2026-03-02 11:31:38.562838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e18ac9c3788'
down_revision: Union[str, None] = '9cf6720485d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('min_rank', sa.Integer(), nullable=True))
    op.drop_column('menu', 'perm_read')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('perm_read', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('menu', 'min_rank')
    # ### end Alembic commands ###
