"""add_user_session_table

Revision ID: 9e675d1048b7
Revises: 5f66f11ed7a4
Create Date: 2026-02-27 10:36:40.369906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e675d1048b7'
down_revision: Union[str, None] = '5f66f11ed7a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_key', sa.String(), nullable=False),
    sa.Column('device_category', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('device_name', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('login_at', sa.DateTime(), nullable=True),
    sa.Column('logout_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_session_device_category'), 'user_session', ['device_category'], unique=False)
    op.create_index(op.f('ix_user_session_last_activity'), 'user_session', ['last_activity'], unique=False)
    op.create_index(op.f('ix_user_session_login_at'), 'user_session', ['login_at'], unique=False)
    op.create_index(op.f('ix_user_session_session_key'), 'user_session', ['session_key'], unique=True)
    op.create_index(op.f('ix_user_session_status'), 'user_session', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_session_status'), table_name='user_session')
    op.drop_index(op.f('ix_user_session_session_key'), table_name='user_session')
    op.drop_index(op.f('ix_user_session_login_at'), table_name='user_session')
    op.drop_index(op.f('ix_user_session_last_activity'), table_name='user_session')
    op.drop_index(op.f('ix_user_session_device_category'), table_name='user_session')
    op.drop_table('user_session')
    # ### end Alembic commands ###
