"""Add versioned dispatch models

Revision ID: a10e386e7ecd
Revises: a5e9dfe53240
Create Date: 2026-05-21 19:54:18.211793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a10e386e7ecd'
down_revision: Union[str, None] = 'a5e9dfe53240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_name', sa.String(length=100), nullable=False),
    sa.Column('route_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('vehicle_count', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_master_end_date'), 'route_master', ['end_date'], unique=False)
    op.create_index(op.f('ix_route_master_start_date'), 'route_master', ['start_date'], unique=False)
    op.create_table('route_timetable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_master_id', sa.Integer(), nullable=False),
    sa.Column('route_name', sa.String(length=100), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('start_location', sa.String(length=100), nullable=False),
    sa.Column('end_location', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['route_master_id'], ['route_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispatch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=False),
    sa.Column('driver_name', sa.String(length=50), nullable=True),
    sa.Column('vehicle_no', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['timetable_id'], ['route_timetable.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_date', 'timetable_id', name='uq_dispatch_date_timetable')
    )
    op.create_index(op.f('ix_dispatch_target_date'), 'dispatch', ['target_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispatch_target_date'), table_name='dispatch')
    op.drop_table('dispatch')
    op.drop_table('route_timetable')
    op.drop_index(op.f('ix_route_master_start_date'), table_name='route_master')
    op.drop_index(op.f('ix_route_master_end_date'), table_name='route_master')
    op.drop_table('route_master')
    # ### end Alembic commands ###
