"""empty message

Revision ID: a325afe14ce7
Revises: d9c93ce716eb
Create Date: 2025-10-13 08:37:08.578249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a325afe14ce7'
down_revision: Union[str, None] = 'd9c93ce716eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('modify_date', sa.DateTime(), nullable=True))
    op.add_column('question', sa.Column('modify_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'modify_date')
    op.drop_column('answer', 'modify_date')
    # ### end Alembic commands ###
