"""Add SystemTask model for async queue

Revision ID: a5e9dfe53240
Revises: 2013b0dbd1a4
Create Date: 2026-05-01 19:52:27.634093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5e9dfe53240'
down_revision: Union[str, None] = '2013b0dbd1a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('unique_key', sa.String(length=100), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('on_parent_failure', sa.String(length=20), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('cron_expression', sa.String(length=50), nullable=True),
    sa.Column('repeat_interval', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('worker_id', sa.String(length=50), nullable=True),
    sa.Column('progress_pct', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('timeout_sec', sa.Integer(), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['system_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_key')
    )
    op.create_index(op.f('ix_system_tasks_correlation_id'), 'system_tasks', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_system_tasks_priority'), 'system_tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_system_tasks_scheduled_at'), 'system_tasks', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_system_tasks_status'), 'system_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_system_tasks_task_type'), 'system_tasks', ['task_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_tasks_task_type'), table_name='system_tasks')
    op.drop_index(op.f('ix_system_tasks_status'), table_name='system_tasks')
    op.drop_index(op.f('ix_system_tasks_scheduled_at'), table_name='system_tasks')
    op.drop_index(op.f('ix_system_tasks_priority'), table_name='system_tasks')
    op.drop_index(op.f('ix_system_tasks_correlation_id'), table_name='system_tasks')
    op.drop_table('system_tasks')
    # ### end Alembic commands ###
