"""Final cleanup and SystemConfig

Revision ID: bb2b9ae50ead
Revises: 9e18ac9c3788
Create Date: 2026-03-02 15:30:21.840386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb2b9ae50ead'
down_revision: Union[str, None] = '9e18ac9c3788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_config',
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_system_config_key'), 'system_config', ['key'], unique=False)
    op.drop_column('alert', 'reset_sec')
    op.drop_column('alert', 'target_users')
    op.drop_column('alert', 'confirm_text')
    op.drop_column('answer', 'modify_date')
    op.alter_column('board_config', 'create_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('dayoff', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('dayoff', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('dayoff', sa.Column('reason', sa.Text(), nullable=True))
    op.alter_column('dayoff', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('uq_user_dayoff_date'), 'dayoff', type_='unique')
    op.drop_column('dayoff', 'memo')
    op.drop_column('dayoff', 'date')
    op.drop_column('dayoff', 'type')
    op.drop_column('dayoff', 'create_date')
    op.drop_column('dayoff', 'category')
    op.drop_constraint(op.f('menu_page_id_fkey'), 'menu', type_='foreignkey')
    op.drop_constraint(op.f('menu_board_id_fkey'), 'menu', type_='foreignkey')
    op.drop_column('menu', 'board_id')
    op.drop_column('menu', 'page_id')
    op.add_column('post', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('post', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('post', sa.Column('delete_date', sa.DateTime(), nullable=True))
    op.alter_column('post', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('push_subscription', 'endpoint',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('push_subscription', 'endpoint',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('post', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('post', 'delete_date')
    op.drop_column('post', 'is_deleted')
    op.drop_column('post', 'content')
    op.add_column('menu', sa.Column('page_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('menu', sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('menu_board_id_fkey'), 'menu', 'board_config', ['board_id'], ['id'])
    op.create_foreign_key(op.f('menu_page_id_fkey'), 'menu', 'post', ['page_id'], ['id'])
    op.add_column('dayoff', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('dayoff', sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('dayoff', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('dayoff', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('dayoff', sa.Column('memo', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('uq_user_dayoff_date'), 'dayoff', ['user_id', 'date'], postgresql_nulls_not_distinct=False)
    op.alter_column('dayoff', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('dayoff', 'reason')
    op.drop_column('dayoff', 'end_date')
    op.drop_column('dayoff', 'start_date')
    op.alter_column('board_config', 'create_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('answer', sa.Column('modify_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('alert', sa.Column('confirm_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('alert', sa.Column('target_users', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('alert', sa.Column('reset_sec', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_system_config_key'), table_name='system_config')
    op.drop_table('system_config')
    # ### end Alembic commands ###
