"""Update Menu model for App integration

Revision ID: bbb562521868
Revises: bf11e5321811
Create Date: 2026-03-03 18:56:28.622472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbb562521868'
down_revision: Union[str, None] = 'bf11e5321811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('app_id', sa.String(), nullable=True))
    op.add_column('menu', sa.Column('app_instance_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('menu_board_id_fkey'), 'menu', type_='foreignkey')
    op.create_foreign_key(None, 'menu', 'app_registry', ['app_id'], ['app_id'])
    op.drop_column('menu', 'board_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'menu', type_='foreignkey')
    op.create_foreign_key(op.f('menu_board_id_fkey'), 'menu', 'board_config', ['board_id'], ['id'])
    op.drop_column('menu', 'app_instance_id')
    op.drop_column('menu', 'app_id')
    # ### end Alembic commands ###
