"""Add AppRegistry model with metadata fields

Revision ID: bf11e5321811
Revises: 6bc38bc7518f
Create Date: 2026-03-03 17:28:18.836065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf11e5321811'
down_revision: Union[str, None] = '6bc38bc7518f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_registry',
    sa.Column('app_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('frontend_route', sa.String(), nullable=True),
    sa.Column('main_component', sa.String(), nullable=True),
    sa.Column('api_module', sa.String(), nullable=True),
    sa.Column('admin_page', sa.String(), nullable=True),
    sa.Column('config_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('min_rank', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('app_id')
    )
    op.create_index(op.f('ix_app_registry_app_id'), 'app_registry', ['app_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_registry_app_id'), table_name='app_registry')
    op.drop_table('app_registry')
    # ### end Alembic commands ###
