"""add_garage_and_regular_duty_columns

Revision ID: d83da6075629
Revises: a10e386e7ecd
Create Date: 2026-05-21 22:12:20.872915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd83da6075629'
down_revision: Union[str, None] = 'a10e386e7ecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_master', sa.Column('is_regular_duty', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('route_timetable', sa.Column('start_garage', sa.String(length=10), nullable=True))
    op.add_column('route_timetable', sa.Column('end_garage', sa.String(length=10), nullable=True))
    op.add_column('route_timetable', sa.Column('is_regular_duty', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.drop_column('route_timetable', 'shift_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_timetable', sa.Column('shift_type', sa.VARCHAR(length=20), server_default=sa.text("'오전'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('route_timetable', 'is_regular_duty')
    op.drop_column('route_timetable', 'end_garage')
    op.drop_column('route_timetable', 'start_garage')
    op.drop_column('route_master', 'is_regular_duty')
    # ### end Alembic commands ###
