"""Add soft delete columns to question

Revision ID: edfaade82409
Revises: b32ffd7781ab
Create Date: 2026-02-18 09:25:59.160857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edfaade82409'
down_revision: Union[str, None] = 'b32ffd7781ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.execute("UPDATE question SET is_deleted = False")
    op.alter_column('question', 'is_deleted', nullable=False)
    op.add_column('question', sa.Column('delete_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'delete_date')
    op.drop_column('question', 'is_deleted')
    # ### end Alembic commands ###
